// ============================================================
// 线索管理模块 — 共享 Mock 数据（第二轮：复合列+新字段）
// ============================================================

import type {
  LeadListItem,
  LeadDetailInfo,
  FollowUpRecord,
  Attachment,
  AssignRecord,
  ReturnRecord,
  TransferRecord,
} from './types';

// --- 附件 Mock ---
const MOCK_ATTACHMENTS: Attachment[] = [
  { id: 'att-1', name: '需求文档.pdf', url: '/files/req.pdf', size: 102400, type: 'application/pdf' },
  { id: 'att-2', name: '报价单.xlsx', url: '/files/quote.xlsx', size: 51200, type: 'application/vnd.ms-excel' },
];

// --- 公海线索 ---
export const PUBLIC_LEADS: LeadListItem[] = [
  {
    key: 'pub-1',
    id: '5944',
    name: '公众号app开发',
    customer: '某餐饮连锁品牌',
    contact: '陈经理',
    phone: '138****8888',
    wechat: 'chenjingli',
    source: '百度',
    keyword: '公众号开发',
    status: '需求调研',
    clueType: 'public',
    level: '高',
    customerLevel: 'A',
    tags: ['小程序', '餐饮'],
    entity: '中科软通',
    owner: '',
    optimizer: '乐炎',
    assistant: '',
    createTime: '2026-08-20 10:32',
    lastFollowTime: '',
    lastFollowContent: '',
    nextFollowTime: '',
    followCount: 0,
    daysHeld: 0,
    budget: 80000,
    remark: '',
    presalesGroupName: '',
    hasGroup: false,
    trashCount: 0,
    transformStatus: false,
    isOverdue: false,
  },
  {
    key: 'pub-2',
    id: '5945',
    name: '物流管理系统定制',
    customer: '某物流公司',
    contact: '刘总',
    phone: '139****9999',
    wechat: '',
    source: '抖音',
    keyword: '物流系统',
    status: '初步沟通',
    clueType: 'public',
    level: '中',
    customerLevel: 'B',
    tags: ['管理系统', '物流'],
    entity: '中科软盈',
    owner: '',
    optimizer: '张三',
    assistant: '',
    createTime: '2026-08-19 14:20',
    lastFollowTime: '',
    lastFollowContent: '',
    nextFollowTime: '',
    followCount: 0,
    daysHeld: 0,
    budget: 50000,
    remark: '',
    hasGroup: false,
    trashCount: 0,
    transformStatus: false,
    isOverdue: false,
  },
  {
    key: 'pub-3',
    id: '5946',
    name: '咖啡店小程序-乐炎',
    customer: '某咖啡连锁',
    contact: '王老师',
    phone: '136****6666',
    wechat: 'wanglaoshi',
    source: '小红书',
    keyword: '咖啡小程序',
    status: '方案报价',
    clueType: 'public',
    level: '高',
    customerLevel: 'S',
    tags: ['小程序', '餐饮'],
    entity: '武汉软艺',
    owner: '',
    optimizer: '乐炎',
    assistant: '',
    createTime: '2026-08-18 16:45',
    lastFollowTime: '',
    lastFollowContent: '',
    nextFollowTime: '',
    followCount: 0,
    daysHeld: 0,
    budget: 120000,
    presalesGroupName: '【0819】咖啡店小程序-乐炎',
    groupType: 'wechat',
    hasGroup: true,
    prototypeLink: 'https://example.com/coffee-prototype',
    trashCount: 0,
    transformStatus: false,
    isOverdue: false,
  },
];

// --- 我的线索（已分配） ---
export const MY_LEADS: LeadListItem[] = [
  {
    key: 'my-1',
    id: '5940',
    name: '某科技公司APP开发需求',
    customer: '北京科技有限公司',
    contact: '张经理',
    phone: '138****1111',
    wechat: 'zhangjingli',
    source: '百度',
    keyword: 'APP开发',
    status: '需求调研',
    clueType: 'assigned',
    level: '高',
    customerLevel: 'S',
    tags: ['APP', '移动应用'],
    entity: '中科软齐',
    owner: '阎杨',
    optimizer: '乐炎',
    assistant: '',
    createTime: '2026-08-19 10:30',
    lastFollowTime: '2026-08-20 10:37',
    lastFollowContent: '已与李总电话初步确认需求，客户希望支持iOS和Android双平台',
    nextFollowTime: '2026-08-21 10:00',
    followCount: 3,
    daysHeld: 1,
    budget: 80000,
    remark: '方便核算成本，新增加',
    presalesGroupName: '【0819】APP开发项目沟通群',
    groupType: 'wecom',
    hasGroup: true,
    historyOwners: '吴丹丹 / 1',
    trashCount: 0,
    transformStatus: false,
    isOverdue: false,
  },
  {
    key: 'my-2',
    id: '5938',
    name: '企业管理系统定制',
    customer: '上海商贸公司',
    contact: '李总',
    phone: '139****2222',
    wechat: '',
    source: '威客',
    keyword: '管理系统',
    status: '方案报价',
    clueType: 'assigned',
    level: '中',
    customerLevel: 'A',
    tags: ['管理系统'],
    entity: '中科软盈',
    owner: '阎杨',
    optimizer: '吴丹丹',
    assistant: '赵六',
    createTime: '2026-08-17 09:00',
    lastFollowTime: '2026-08-19 15:40',
    lastFollowContent: '已通过微信好友，发送案例库，等待客户反馈',
    nextFollowTime: '2026-08-20 14:00',
    followCount: 5,
    daysHeld: 3,
    budget: 60000,
    hasGroup: false,
    trashCount: 0,
    transformStatus: false,
    isOverdue: true, // 今日到期
  },
  {
    key: 'my-3',
    id: '5935',
    name: '电商小程序开发',
    customer: '深圳电商公司',
    contact: '王总',
    phone: '136****3333',
    wechat: 'wangzong',
    source: '小红书',
    keyword: '电商小程序',
    status: '合同洽谈',
    clueType: 'assigned',
    level: '高',
    customerLevel: 'S',
    tags: ['小程序', '电商'],
    entity: '中科网联',
    owner: '阎杨',
    optimizer: '阎杨',
    assistant: '吴丹丹',
    createTime: '2026-08-10 14:20',
    lastFollowTime: '2026-08-18 16:00',
    lastFollowContent: '与王总确认合同条款，客户要求分期付款',
    nextFollowTime: '2026-08-15 09:00', // 已逾期
    followCount: 12,
    daysHeld: 10,
    budget: 150000,
    presalesGroupName: '【电商小程序】项目群',
    groupType: 'feishu',
    hasGroup: true,
    prototypeLink: 'https://example.com/ecommerce-proto',
    historyOwners: '张三 / 2',
    trashCount: 0,
    transformStatus: false,
    isOverdue: true, // 已逾期
  },
  {
    key: 'my-4',
    id: '5932',
    name: '数据分析平台',
    customer: '广州金融公司',
    contact: '赵经理',
    phone: '137****4444',
    wechat: '',
    source: '互站',
    keyword: '数据分析',
    status: '初步沟通',
    clueType: 'assigned',
    level: '低',
    customerLevel: 'C',
    tags: ['数据分析'],
    entity: '中科软通',
    owner: '阎杨',
    optimizer: '',
    assistant: '',
    createTime: '2026-08-15 11:00',
    lastFollowTime: '2026-08-17 09:00',
    lastFollowContent: '客户表示暂时没有需求，后续再联系',
    nextFollowTime: '2026-08-25 09:00',
    followCount: 2,
    daysHeld: 5,
    budget: 30000,
    hasGroup: false,
    trashCount: 0,
    transformStatus: false,
    isOverdue: false,
  },
];

// --- 我录入的线索 ---
export const MY_CREATED_LEADS: LeadListItem[] = [
  MY_LEADS[0], // optimizer = 当前用户
];

// --- 我协助的线索 ---
export const MY_ASSISTED_LEADS: LeadListItem[] = [
  MY_LEADS[2], // assistant = 当前用户
];

// --- 全部线索（合并视图） ---
export const ALL_LEADS: LeadListItem[] = [
  ...PUBLIC_LEADS,
  ...MY_LEADS,
  {
    key: 'trash-1',
    id: '5920',
    name: '某餐饮APP虚假需求',
    customer: '',
    contact: '张某',
    phone: '138****0000',
    wechat: '',
    source: '百度',
    keyword: '餐饮APP',
    status: '未联系',
    clueType: 'trash',
    level: '低',
    tags: ['小程序', '餐饮'],
    entity: '中科软齐',
    owner: '',
    optimizer: '吴丹丹',
    assistant: '',
    createTime: '2026-08-10 10:30',
    lastFollowTime: '',
    lastFollowContent: '',
    nextFollowTime: '',
    followCount: 0,
    daysHeld: 0,
    trashReason: '重复线索，已在系统中存在',
    trashCount: 1,
    transformStatus: false,
    isOverdue: false,
  },
  {
    key: 'closed-1',
    id: '5900',
    name: '华信科技内部OA流程优化需求',
    customer: '华信科技有限公司',
    contact: '周经理',
    phone: '138****9999',
    wechat: 'huaxin-zhou',
    source: '豆包',
    keyword: 'OA流程优化',
    status: '已签单',
    clueType: 'assigned',
    level: '高',
    customerLevel: 'S',
    tags: ['OA系统', '流程管理'],
    entity: '中科软齐',
    owner: '阎杨',
    optimizer: '吴丹丹',
    assistant: '赵六',
    createTime: '2026-07-05 14:20',
    lastFollowTime: '2026-08-01 16:30',
    lastFollowContent: '合同已签署，首期款到账',
    nextFollowTime: '',
    followCount: 15,
    daysHeld: 46,
    budget: 960000,
    hasGroup: true,
    trashCount: 0,
    transformStatus: true,
    isOverdue: false,
  },
];

// --- 垃圾线索 ---
export const TRASH_LEADS: LeadListItem[] = [
  ALL_LEADS.find((l) => l.key === 'trash-1')!,
  {
    key: 'trash-2',
    id: '5918',
    name: '无效联系方式',
    customer: '',
    contact: '王某',
    phone: '139****1111',
    wechat: '',
    source: '抖音',
    keyword: '',
    status: '未联系',
    clueType: 'trash',
    level: '低',
    tags: ['APP'],
    entity: '中科软盈',
    owner: '',
    optimizer: '张三',
    assistant: '',
    createTime: '2026-08-08 14:20',
    lastFollowTime: '',
    lastFollowContent: '',
    nextFollowTime: '',
    followCount: 0,
    daysHeld: 0,
    trashReason: '电话无法接通，疑似虚假信息',
    trashCount: 1,
    transformStatus: false,
    isOverdue: false,
  },
  {
    key: 'trash-3',
    id: '5915',
    name: '恶意询价',
    customer: '',
    contact: '刘某',
    phone: '136****2222',
    wechat: '',
    source: '小红书',
    keyword: '',
    status: '未联系',
    clueType: 'trash',
    level: '无意向',
    tags: ['管理系统'],
    entity: '中科网联',
    owner: '',
    optimizer: '赵六',
    assistant: '',
    createTime: '2026-08-05 16:45',
    lastFollowTime: '',
    lastFollowContent: '',
    nextFollowTime: '',
    followCount: 0,
    daysHeld: 0,
    trashReason: '多次询价从未签单，浪费时间',
    trashCount: 3, // 第 3 次退回自动标记垃圾
    transformStatus: false,
    isOverdue: false,
  },
];

// --- 已成交线索 ---
export const CLOSED_LEADS: LeadListItem[] = [
  ALL_LEADS.find((l) => l.key === 'closed-1')!,
];

// --- 跟进记录 Mock ---
export const FOLLOWUP_RECORDS: FollowUpRecord[] = [
  {
    id: 'fu-1',
    leadId: '5940',
    method: '电话',
    customerStatus: '需求调研',
    customerLevel: 'S',
    content: '与张经理电话沟通了APP开发的核心需求，客户希望支持iOS和Android双平台，包含考勤、审批、通知等模块。客户预算在50-80万之间。',
    nextFollowTime: '2026-08-21 10:00',
    costHours: 0,
    costMins: 35,
    attachments: [],
    creator: '阎杨',
    createdAt: '2026-08-20 10:37',
    updatedAt: '2026-08-20 10:37',
    followupStatus: 'done',
  },
  {
    id: 'fu-2',
    leadId: '5940',
    method: '微信',
    customerStatus: '初步沟通',
    content: '已通过微信好友，发送案例库，等待客户反馈。',
    nextFollowTime: '2026-08-20 10:00',
    costHours: 0,
    costMins: 10,
    attachments: [MOCK_ATTACHMENTS[0]],
    creator: '阎杨',
    createdAt: '2026-08-19 15:40',
    updatedAt: '2026-08-19 15:40',
    followupStatus: 'done',
  },
  {
    id: 'fu-3',
    leadId: '5940',
    method: '其他',
    customerStatus: '初步沟通',
    content: '线索由投放渠道自动录入，初始信息已记录。',
    nextFollowTime: '2026-08-20 10:00',
    attachments: [],
    creator: '系统',
    createdAt: '2026-08-19 10:30',
    updatedAt: '2026-08-19 10:30',
    followupStatus: 'done',
  },
  {
    id: 'fu-4',
    leadId: '5935',
    method: '电话',
    customerStatus: '合同洽谈',
    content: '与王总确认合同条款，客户要求分期付款，已提交报价审批。',
    nextFollowTime: '2026-08-19 09:00',
    costHours: 0,
    costMins: 20,
    attachments: [MOCK_ATTACHMENTS[1]],
    creator: '阎杨',
    createdAt: '2026-08-18 16:00',
    updatedAt: '2026-08-18 16:00',
    followupStatus: 'pending', // 待跟进（已逾期）
  },
];

// --- 分配记录 Mock ---
export const ASSIGN_RECORDS: AssignRecord[] = [
  {
    id: 'asgn-1',
    leadId: '5940',
    fromOwner: '',
    toOwner: '阎杨',
    reason: '新线索分配',
    operator: '系统',
    createdAt: '2026-08-19 11:20',
  },
];

// --- 退回记录 Mock ---
export const RETURN_RECORDS: ReturnRecord[] = [
  { id: 'ret-1', leadId: '5915', reason: '客户明确表示无需求', operator: '张三', createdAt: '2026-08-07 10:00', returnCount: 1 },
  { id: 'ret-2', leadId: '5915', reason: '联系方式无效', operator: '吴丹丹', createdAt: '2026-08-08 14:00', returnCount: 2 },
  { id: 'ret-3', leadId: '5915', reason: '多次跟进无进展', operator: '赵六', createdAt: '2026-08-09 09:00', returnCount: 3 },
];

// --- 流转记录 Mock ---
export const TRANSFER_RECORDS: TransferRecord[] = [
  // 5940 某科技公司APP开发需求
  { id: 'tr-1', leadId: '5940', operator: '系统', action: 'assign', toOwner: '阎杨', status: '初步沟通', reason: '新线索分配', createdAt: '2026-08-19 11:20' },
  { id: 'tr-2', leadId: '5940', operator: '阎杨', action: 'claim', toOwner: '阎杨', status: '初步沟通', reason: '', createdAt: '2026-08-19 11:25' },
  // 5935 电商小程序开发
  { id: 'tr-3', leadId: '5935', operator: '系统', action: 'assign', toOwner: '张三', status: '初步沟通', reason: '新线索分配', createdAt: '2026-08-10 15:00' },
  { id: 'tr-4', leadId: '5935', operator: '张三', action: 'transfer', toOwner: '阎杨', status: '需求调研', reason: '客户要求技术负责人对接', createdAt: '2026-08-12 09:00' },
  { id: 'tr-5', leadId: '5935', operator: '阎杨', action: 'assign', toOwner: '阎杨', status: '方案报价', reason: '', createdAt: '2026-08-14 10:00' },
  // 5915 恶意询价（3次退回）
  { id: 'tr-6', leadId: '5915', operator: '张三', action: 'return', toOwner: '', status: '未联系', reason: '客户明确表示无需求', createdAt: '2026-08-07 10:00' },
  { id: 'tr-7', leadId: '5915', operator: '吴丹丹', action: 'return', toOwner: '', status: '未联系', reason: '联系方式无效', createdAt: '2026-08-08 14:00' },
  { id: 'tr-8', leadId: '5915', operator: '赵六', action: 'return', toOwner: '', status: '垃圾线索', reason: '多次跟进无进展', createdAt: '2026-08-09 09:00' },
  { id: 'tr-9', leadId: '5915', operator: '系统', action: 'trash', toOwner: '', status: '垃圾线索', reason: '第3次退回自动标记', createdAt: '2026-08-09 09:00' },
  // 5900 华信科技OA（已转客户）
  { id: 'tr-10', leadId: '5900', operator: '系统', action: 'assign', toOwner: '阎杨', status: '初步沟通', reason: '新线索分配', createdAt: '2026-07-05 15:10' },
  { id: 'tr-11', leadId: '5900', operator: '阎杨', action: 'transfer', toOwner: '吴丹丹', status: '需求调研', reason: '优化师跟进', createdAt: '2026-07-10 10:00' },
  { id: 'tr-12', leadId: '5900', operator: '吴丹丹', action: 'transform', toOwner: '阎杨', status: '已签单', reason: '客户签约', createdAt: '2026-08-01 16:30' },
];

/** 按线索ID获取流转记录 */
export function getTransferRecordsByLeadId(leadId: string): TransferRecord[] {
  return TRANSFER_RECORDS.filter((r) => r.leadId === leadId);
}

// --- 线索详情 Mock（扩展版） ---
export function getLeadDetailInfo(leadId: string): LeadDetailInfo | null {
  const leads: Record<string, LeadDetailInfo> = {
    '5944': {
      name: '公众号app开发',
      customer: '某餐饮连锁品牌',
      contact: '陈经理',
      phone: '13888888888',
      wechat: 'chenjingli',
      source: '百度',
      keyword: '公众号开发',
      tags: ['小程序', '餐饮'],
      requirement: '需要开发餐饮连锁品牌微信小程序，支持门店点餐、会员积分、优惠券核销及后台运营管理。',
      initialRequirement: '公众号app开发定制需求',
      level: '高',
      customerLevel: 'A',
      status: '需求调研',
      clueType: 'public',
      transformStatus: false,
      trashCount: 0,
      createTime: '2026-08-20 10:32',
      updateTime: '2026-08-20 10:32',
      claimTime: '',
      lastFollowTime: '',
      nextFollowTime: '',
      creator: '系统',
      owner: '',
      optimizer: '乐炎',
      assistant: '',
      customerTitle: '陈经理',
      customerCost: '',
      entity: '中科软通',
      agent: '乐炎',
      followCount: 0,
      daysHeld: 0,
      attachments: [],
    },
    '5940': {
      name: '某科技公司APP开发需求',
      customer: '北京科技有限公司',
      contact: '张经理',
      phone: '13800138000',
      wechat: 'zhangjingli',
      source: '百度',
      keyword: 'APP开发',
      tags: ['APP', '移动应用'],
      requirement: '需要开发一款企业内部管理APP，支持iOS和Android双平台，包含考勤、审批、通知等功能模块。',
      initialRequirement: 'APP开发需求',
      level: '高',
      customerLevel: 'S',
      status: '需求调研',
      clueType: 'assigned',
      transformStatus: false,
      trashCount: 0,
      createTime: '2026-08-19 10:30',
      updateTime: '2026-08-20 10:37',
      claimTime: '2026-08-19 11:20',
      lastFollowTime: '2026-08-20 10:37',
      nextFollowTime: '2026-08-21 10:00',
      creator: '阎杨',
      owner: '阎杨',
      optimizer: '乐炎',
      assistant: '',
      customerTitle: '张经理',
      customerCost: '12,000',
      entity: '中科软齐',
      agent: '乐炎',
      customerBudget: '¥80,000',
      presalesGroupName: '【0819】APP开发项目沟通群',
      followCount: 3,
      daysHeld: 1,
      attachments: MOCK_ATTACHMENTS,
    },
    '5935': {
      name: '电商小程序开发',
      customer: '深圳电商公司',
      contact: '王总',
      phone: '13600136000',
      wechat: 'wangzong',
      source: '小红书',
      keyword: '电商小程序',
      tags: ['小程序', '电商'],
      requirement: '开发电商小程序，支持商品展示、购物车、在线支付、订单管理、会员体系等功能。',
      initialRequirement: '电商小程序开发',
      level: '高',
      customerLevel: 'S',
      status: '合同洽谈',
      clueType: 'assigned',
      transformStatus: false,
      trashCount: 0,
      createTime: '2026-08-10 14:20',
      updateTime: '2026-08-18 16:00',
      claimTime: '2026-08-10 15:00',
      lastFollowTime: '2026-08-18 16:00',
      nextFollowTime: '2026-08-15 09:00',
      creator: '阎杨',
      owner: '阎杨',
      optimizer: '阎杨',
      assistant: '吴丹丹',
      customerTitle: '王总',
      customerCost: '8,000',
      entity: '中科网联',
      agent: '',
      customerBudget: '¥150,000',
      presalesGroupName: '【电商小程序】项目群',
      followCount: 12,
      daysHeld: 10,
      attachments: [],
    },
    '5900': {
      name: '华信科技内部OA流程优化需求',
      customer: '华信科技有限公司',
      contact: '周经理',
      phone: '13800009999',
      wechat: 'huaxin-zhou',
      source: '豆包',
      keyword: 'OA流程优化',
      tags: ['OA系统', '流程管理', '审批'],
      requirement: '建设内部 OA 流程优化系统，优先覆盖审批、合同、项目协同和日报管理，并与现有组织架构及 SSO 登录对接。',
      initialRequirement: '华信科技内部OA流程优化',
      level: '高',
      customerLevel: 'S',
      status: '已签单',
      clueType: 'assigned',
      transformStatus: true,
      trashCount: 0,
      createTime: '2026-07-05 14:20',
      updateTime: '2026-08-01 16:30',
      claimTime: '2026-07-05 15:10',
      lastFollowTime: '2026-08-01 16:30',
      nextFollowTime: '',
      creator: '阎杨',
      owner: '阎杨',
      optimizer: '吴丹丹',
      assistant: '赵六',
      customerTitle: '周经理',
      customerCost: '12,000',
      entity: '中科软齐',
      customerType: '企业客户',
      customerBudget: '¥960,000',
      presalesGroupName: '华信科技 OA 项目群',
      groupType: 'dingtalk',
      prototypeLink: 'https://example.com/huaxin-oa-prototype',
      customerNote: '客户要求一期优先交付审批、合同和项目协同能力。',
      followCount: 15,
      daysHeld: 46,
      attachments: [],
    },
  };

  return leads[leadId] || null;
}

// --- 搜索字段列表 ---
export const SEARCH_FIELDS = [
  { label: '线索名称', value: 'name' },
  { label: '线索ID', value: 'id' },
  { label: '电话', value: 'phone' },
  { label: '微信', value: 'wechat' },
  { label: '威客ID', value: 'witkeyId' },
  { label: '任务编号', value: 'witkeyTaskNo' },
  { label: '联系人', value: 'contact' },
  { label: '来源', value: 'source' },
  { label: '所属公司', value: 'customer' },
  { label: '客户等级', value: 'customerLevel' },
  { label: '客户状态', value: 'status' },
  { label: '优化师', value: 'optimizer' },
  { label: '负责人', value: 'owner' },
  { label: '协助人', value: 'assistant' },
  { label: '创建时间', value: 'createTime' },
  { label: '下次跟进时间', value: 'nextFollowTime' },
] as const;
