// src/app/pages/delivery-plan/sopTemplate.ts

/** SOP 步骤模板 */
export interface SopStepTemplate {
  /** 步骤编号，如 '1.1' */
  stepNo: string;
  /** 步骤名称 */
  stepName: string;
  /** 所属板块号 */
  phaseNo: number;
  /** 负责部门 */
  department: string;
  /** 负责人角色 */
  assigneeRole: string;
  /** 预估工期（天） */
  durationDays: number;
  /** 步骤描述 */
  description: string;
  /** 关键注意事项 */
  notes: string;
  /** 涉及工具 */
  tools: string;
  /** 交付物 */
  deliverables: string;
  /** 是否常驻步骤（如需求变更管理） */
  isEvergreen: boolean;
}

/** 步骤依赖映射：步骤编号 → 前置步骤编号数组 */
export const SOP_STEP_DEPENDENCIES: Record<string, string[]> = {
  '1.2': ['1.1'],
  '1.3': ['1.2'],
  '1.4': ['1.3'],
  '1.5': ['1.4'],
  '2.1': ['1.5'],
  '2.2': ['2.1'],
  '2.3': ['2.2'],
  '2.4': ['2.3'],
  '3.1': ['2.4'],
  '3.2': ['3.1'],
  '3.3': ['3.2'],
  '3.4': ['3.3'],
  '3.5': ['3.3'],
  '3.6': ['3.5'],
  '3.7': ['3.4'],
  '3.9': ['3.7'],
  '3.10': ['3.9'],
  // 3.8 为常驻步骤，无前置依赖
  '4.2': ['4.1'],
  '4.3': ['4.1'],
  '4.4': ['4.3'],
  '4.5': ['4.3'],
  '4.6': ['4.4'],
  '4.7': [],
  '5.1': ['3.10'],
  '5.2': ['5.1'],
  '5.3': ['5.2'],
  '5.4': ['5.3'],
  '5.5': ['5.4'],
  '6.1': ['5.5'],
  '6.2': ['6.1'],
  '6.3': ['6.1'],
  '6.4': ['6.3'],
  '6.5': ['6.1'],
  '7.1': ['6.1'],
  '7.2': ['7.1'],
  '7.3': ['7.1'],
  '7.4': ['7.1'],
  '7.5': ['7.3'],
};

/** 板块依赖映射：板块号 → 前置板块号数组 */
export const SOP_PHASE_DEPENDENCIES: Record<number, number[]> = {
  2: [1],
  3: [2],
  4: [2],
  5: [3, 4],
  6: [5],
  7: [6],
};

/** 模板版本号 */
export const SOP_TEMPLATE_VERSION = '1.0';

/** 全部 37 个 SOP 步骤模板 */
export const SOP_STEP_TEMPLATES: SopStepTemplate[] = [
  // ──────── Phase 1：合同交接 ────────
  {
    stepNo: '1.1',
    stepName: '合同接收与存档',
    phaseNo: 1,
    department: '售前组、法务组',
    assigneeRole: '销售',
    durationDays: 1,
    description: '接收客户签署的正式合同，核对合同条款与附件完整性，完成系统存档与编号。',
    notes: '务必确认合同已双方盖章签字，缺失页或模糊条款需立即反馈。',
    tools: 'OA 系统、合同管理平台、扫描仪',
    deliverables: '已存档合同扫描件、合同登记表',
    isEvergreen: false,
  },
  {
    stepNo: '1.2',
    stepName: '合同核心要素拆解',
    phaseNo: 1,
    department: '售前组、交付组、法务组',
    assigneeRole: '产品经理',
    durationDays: 1,
    description: '从合同中提取项目范围、交付物清单、里程碑节点、付款条件等核心要素，形成结构化摘要。',
    notes: '范围边界与验收标准必须逐条明确，避免后期歧义。',
    tools: 'Excel/在线表格、项目管理工具、合同文本',
    deliverables: '合同要素拆解表、范围说明书',
    isEvergreen: false,
  },
  {
    stepNo: '1.3',
    stepName: '客户初步需求调研',
    phaseNo: 1,
    department: '客户、销售',
    assigneeRole: '产品经理',
    durationDays: 2,
    description: '与客户关键干系人沟通，收集核心业务需求、期望功能和使用场景，形成初步需求清单。',
    notes: '优先确认客户决策链和对接窗口人，需求记录需客户确认回签。',
    tools: '在线问卷、会议纪要模板、需求管理工具',
    deliverables: '初步需求清单、会议纪要、干系人联络表',
    isEvergreen: false,
  },
  {
    stepNo: '1.4',
    stepName: '项目可行性评估',
    phaseNo: 1,
    department: '开发组、运维组、管理层',
    assigneeRole: '产品经理',
    durationDays: 2,
    description: '从技术实现、资源排期、合规风险三个维度评估项目可行性，输出评估结论与风险清单。',
    notes: '若存在重大技术风险或资源冲突，须在立项前上报管理层决策。',
    tools: '项目管理工具、风险评估模板、技术评审记录',
    deliverables: '可行性评估报告、风险清单',
    isEvergreen: false,
  },
  {
    stepNo: '1.5',
    stepName: '客户对接群组建 & 人员介绍',
    phaseNo: 1,
    department: '客户、销售',
    assigneeRole: '销售',
    durationDays: 1,
    description: '建立项目专属沟通群，完成双方团队人员介绍与角色对应，确认沟通机制与响应时效。',
    notes: '群内须明确各方对接人角色，避免信息多头或遗漏。',
    tools: '企业微信/钉钉、项目通讯录模板',
    deliverables: '客户对接群、人员联络表',
    isEvergreen: false,
  },

  // ──────── Phase 2：项目启动准备 ────────
  {
    stepNo: '2.1',
    stepName: '项目立项与审批',
    phaseNo: 2,
    department: '管理层、财务部',
    assigneeRole: '项目经理',
    durationDays: 2,
    description: '编制立项申请，经管理层与财务部审批通过后正式立项，明确项目预算与成本控制线。',
    notes: '审批未通过前不可启动后续资源调配，预算需与合同付款节点对齐。',
    tools: 'OA 审批系统、项目立项模板、财务系统',
    deliverables: '立项审批单、项目预算表',
    isEvergreen: false,
  },
  {
    stepNo: '2.2',
    stepName: '项目团队组建与分工',
    phaseNo: 2,
    department: '开发组、UI 组、测试组、运维组',
    assigneeRole: '项目经理',
    durationDays: 3,
    description: '根据项目规模调配各角色人员，明确职责分工与汇报关系，完成团队组建。',
    notes: '关键岗位须指定AB角，确保人员变动时项目不受影响。',
    tools: '项目管理工具、组织架构模板、人员排期表',
    deliverables: '项目团队通讯录、职责分工矩阵',
    isEvergreen: false,
  },
  {
    stepNo: '2.3',
    stepName: '全项目计划编制',
    phaseNo: 2,
    department: '全项目组、客户',
    assigneeRole: '项目经理',
    durationDays: 3,
    description: '编制涵盖各板块时间节点、里程碑、资源需求的全项目计划，与客户确认关键交付日期。',
    notes: '计划需留有合理缓冲，客户确认后作为后续变更基准。',
    tools: '甘特图工具、项目管理工具、计划评审模板',
    deliverables: '项目整体计划书、里程碑计划表',
    isEvergreen: false,
  },
  {
    stepNo: '2.4',
    stepName: '软硬件 & 第三方资源前置部署',
    phaseNo: 2,
    department: '运维组、开发组',
    assigneeRole: '运维专员',
    durationDays: 2,
    description: '提前采购和部署服务器、域名、第三方API、数据库等基础资源，确保开发环境就绪。',
    notes: '第三方服务需确认合同条款与调用量限制，避免开发中途受限。',
    tools: '云服务商控制台、配置管理工具、采购审批系统',
    deliverables: '资源部署清单、环境就绪确认单',
    isEvergreen: false,
  },

  // ──────── Phase 3：项目交付执行 ────────
  {
    stepNo: '3.1',
    stepName: '需求文档编制 & 内部评审',
    phaseNo: 3,
    department: '开发组、交付组',
    assigneeRole: '产品经理',
    durationDays: 3,
    description: '基于调研结果编写详细需求规格文档，组织开发组内部评审并定稿。',
    notes: '需求文档需与合同要素拆解表逐项对照，确保无遗漏无越界。',
    tools: '文档协作平台、需求管理工具、评审记录模板',
    deliverables: '需求规格说明书、内部评审记录',
    isEvergreen: false,
  },
  {
    stepNo: '3.2',
    stepName: '原型设计',
    phaseNo: 3,
    department: '内部设计组',
    assigneeRole: '产品经理',
    durationDays: 5,
    description: '根据需求文档设计交互原型，覆盖全部核心业务流程与页面布局。',
    notes: '原型须标注关键交互逻辑与异常流程，复杂页面需附带状态说明。',
    tools: 'Axure/Figma、设计规范库、原型评审模板',
    deliverables: '交互原型文件、页面流程图',
    isEvergreen: false,
  },
  {
    stepNo: '3.3',
    stepName: '原型设计客户确认',
    phaseNo: 3,
    department: '客户、销售',
    assigneeRole: '产品经理',
    durationDays: 2,
    description: '向客户演示原型方案，收集反馈并完成修改，取得客户书面确认。',
    notes: '客户确认须以书面或邮件形式留存，口头确认无效。',
    tools: '原型演示工具、邮件系统、确认函模板',
    deliverables: '客户确认函、原型修改记录',
    isEvergreen: false,
  },
  {
    stepNo: '3.4',
    stepName: '开发交底 & 技术方案设计',
    phaseNo: 3,
    department: '开发组',
    assigneeRole: '开发主管',
    durationDays: 2,
    description: '组织开发团队需求交底会议，完成技术架构设计与数据库方案，输出技术方案文档。',
    notes: '技术方案须评估性能、安全、扩展性，涉及第三方集成的需提前验证可行性。',
    tools: '架构设计工具、API 文档工具、技术评审模板',
    deliverables: '技术方案文档、数据库设计文档、API 接口清单',
    isEvergreen: false,
  },
  {
    stepNo: '3.5',
    stepName: 'UI 设计',
    phaseNo: 3,
    department: '内部 UI 组',
    assigneeRole: 'UI 设计师',
    durationDays: 5,
    description: '基于确认原型进行视觉设计，输出高保真设计稿与切图资源。',
    notes: '设计稿须适配目标平台尺寸规范，切图命名需符合开发规范。',
    tools: 'Figma/Sketch、设计标注工具、切图导出工具',
    deliverables: '高保真设计稿、切图资源包、设计规范说明',
    isEvergreen: false,
  },
  {
    stepNo: '3.6',
    stepName: 'UI 设计客户确认',
    phaseNo: 3,
    department: '客户、销售',
    assigneeRole: 'UI 设计师',
    durationDays: 2,
    description: '向客户展示高保真设计稿，收集反馈并完成调整，取得客户书面确认。',
    notes: '确认后UI设计将作为开发基准，后续修改按变更流程处理。',
    tools: '设计稿演示工具、邮件系统、确认函模板',
    deliverables: '客户确认函、UI 修改记录',
    isEvergreen: false,
  },
  {
    stepNo: '3.7',
    stepName: '开发过程每日跟进',
    phaseNo: 3,
    department: '开发组、运维组',
    assigneeRole: '产品经理',
    durationDays: 15,
    description: '每日组织站会跟进开发进度，协调资源与阻塞问题，确保按计划推进。',
    notes: '阻塞问题须当日升级，进度偏差超2天需及时预警并调整计划。',
    tools: '项目管理工具、站会记录模板、缺陷跟踪系统',
    deliverables: '每日站会纪要、进度周报、问题跟踪表',
    isEvergreen: false,
  },
  {
    stepNo: '3.8',
    stepName: '需求变更全流程管理',
    phaseNo: 3,
    department: '客户、销售、开发组、运维组',
    assigneeRole: '产品经理',
    durationDays: 0,
    description: '贯穿项目全生命周期，对客户提出的需求变更进行评估、审批、排期和跟踪，确保变更可控。',
    notes: '所有变更必须走书面审批流程，严禁口头承诺直接开发，需评估对工期和成本的影响。',
    tools: '变更管理工具、OA 审批系统、影响评估模板',
    deliverables: '变更申请单、变更影响评估报告、变更实施记录',
    isEvergreen: true,
  },
  {
    stepNo: '3.9',
    stepName: '阶段性节点交付',
    phaseNo: 3,
    department: '客户、销售',
    assigneeRole: '产品经理',
    durationDays: 3,
    description: '按里程碑计划完成阶段性成果交付与演示，取得客户阶段性确认。',
    notes: '阶段性交付须同步推进收款节点，客户确认后作为下一阶段启动前提。',
    tools: '项目管理工具、交付确认模板、演示工具',
    deliverables: '阶段交付确认单、阶段演示记录',
    isEvergreen: false,
  },
  {
    stepNo: '3.10',
    stepName: '收款节点跟进',
    phaseNo: 3,
    department: '客户、销售',
    assigneeRole: '销售',
    durationDays: 2,
    description: '根据合同付款条件与交付进度，跟进客户各期款项支付，确保资金回笼。',
    notes: '逾期未付款项须及时升级至管理层，避免资金风险。',
    tools: '财务系统、合同管理平台、催款通知模板',
    deliverables: '收款跟进记录、催款通知',
    isEvergreen: false,
  },

  // ──────── Phase 4：资质备案 & 上架 ────────
  {
    stepNo: '4.1',
    stepName: '域名注册与实名认证',
    phaseNo: 4,
    department: '运维组、客户',
    assigneeRole: '运维专员',
    durationDays: 3,
    description: '完成项目所需域名的注册、实名认证及DNS解析配置。',
    notes: '域名须以客户主体注册，实名认证资料需提前与客户确认。',
    tools: '域名注册商平台、DNS 管理工具、实名认证系统',
    deliverables: '域名注册证书、实名认证通过截图',
    isEvergreen: false,
  },
  {
    stepNo: '4.2',
    stepName: 'SSL 证书申请、签发与配置',
    phaseNo: 4,
    department: '运维组、客户',
    assigneeRole: '运维专员',
    durationDays: 5,
    description: '申请SSL证书，完成域名验证、证书签发及服务器端HTTPS配置。',
    notes: '企业级证书需客户提供营业执照等资料，配置后需验证全站HTTPS可达。',
    tools: '证书签发平台、Web 服务器配置工具、SSL 检测工具',
    deliverables: 'SSL 证书文件、HTTPS 配置确认单',
    isEvergreen: false,
  },
  {
    stepNo: '4.3',
    stepName: '网站 ICP 备案',
    phaseNo: 4,
    department: '运维组、客户',
    assigneeRole: '运维专员',
    durationDays: 15,
    description: '准备备案资料并提交ICP备案申请，跟踪审核进度直至备案通过。',
    notes: 'ICP备案周期较长且不可加急，须尽早启动；资料不全会导致退回重审。',
    tools: '备案管理系统、管局审核平台、资料清单模板',
    deliverables: 'ICP 备案号、备案通过通知',
    isEvergreen: false,
  },
  {
    stepNo: '4.4',
    stepName: '小程序专项资质 & 第三方配置',
    phaseNo: 4,
    department: '运维组、产品经理、客户',
    assigneeRole: '运维专员',
    durationDays: 5,
    description: '办理小程序所需类目资质，完成微信开放平台注册与第三方接口配置。',
    notes: '特殊行业需前置资质审批，需与客户确认营业执照经营范围是否覆盖。',
    tools: '微信公众平台、开放平台管理后台、资质申请系统',
    deliverables: '小程序类目资质、第三方接口配置文档',
    isEvergreen: false,
  },
  {
    stepNo: '4.5',
    stepName: 'APP 上架准备（安卓/iOS）',
    phaseNo: 4,
    department: '运维组、测试组、客户',
    assigneeRole: '运维专员',
    durationDays: 7,
    description: '准备APP上架所需资料、隐私政策、应用截图等，完成各应用市场开发者账号与配置。',
    notes: 'iOS 上架需Apple开发者账号及审核资料，安卓各市场要求不一需逐个准备。',
    tools: 'App Store Connect、安卓应用市场后台、隐私政策生成工具',
    deliverables: '上架资料包、开发者账号配置确认',
    isEvergreen: false,
  },
  {
    stepNo: '4.6',
    stepName: 'APP/小程序正式提审与跟进',
    phaseNo: 4,
    department: '运维组、产品经理',
    assigneeRole: '运维专员',
    durationDays: 7,
    description: '提交APP与小程序审核申请，跟踪审核进度，处理审核反馈直至通过上架。',
    notes: '审核被拒需及时响应修改，常见拒审原因包括隐私合规和支付合规问题。',
    tools: '各平台审核后台、版本管理工具、审核反馈跟踪表',
    deliverables: '审核通过通知、上架确认截图',
    isEvergreen: false,
  },
  {
    stepNo: '4.7',
    stepName: '软件著作权申请',
    phaseNo: 4,
    department: '运维组、产品经理、客户',
    assigneeRole: '运维专员',
    durationDays: 30,
    description: '准备软件著作权申请材料，提交中国版权保护中心并跟踪审批进度。',
    notes: '软著申请周期长，可与其他上架步骤并行推进，不影响主流程。',
    tools: '中国版权保护中心系统、申请材料模板、进度跟踪表',
    deliverables: '软件著作权登记证书、申请回执',
    isEvergreen: false,
  },

  // ──────── Phase 5：测试验收 ────────
  {
    stepNo: '5.1',
    stepName: '项目综合内部测试',
    phaseNo: 5,
    department: '开发组、测试组',
    assigneeRole: '测试工程师',
    durationDays: 5,
    description: '执行功能测试、集成测试与兼容性测试，覆盖全部需求用例，记录并分级所有缺陷。',
    notes: 'P0/P1级缺陷必须在交付客户前修复完毕，测试覆盖率需达标。',
    tools: '测试管理平台、缺陷跟踪系统、自动化测试工具',
    deliverables: '测试用例集、缺陷清单、测试报告',
    isEvergreen: false,
  },
  {
    stepNo: '5.2',
    stepName: '性能 & 安全 & 合规专项测试',
    phaseNo: 5,
    department: '测试组、运维组',
    assigneeRole: '测试工程师',
    durationDays: 3,
    description: '执行性能压测、安全漏洞扫描与合规性检查，确保系统满足非功能性要求。',
    notes: '安全高危漏洞须立即修复，合规问题涉及法律风险不可延迟处理。',
    tools: '性能压测工具、安全扫描工具、合规检查清单',
    deliverables: '性能测试报告、安全扫描报告、合规检查表',
    isEvergreen: false,
  },
  {
    stepNo: '5.3',
    stepName: '客户交付演示 & 预验收',
    phaseNo: 5,
    department: '客户',
    assigneeRole: '产品经理',
    durationDays: 2,
    description: '向客户完整演示系统功能，收集预验收反馈并整理待整改清单。',
    notes: '演示环境需与生产环境一致，避免演示与实际体验差异导致客户质疑。',
    tools: '演示环境、屏幕共享工具、反馈收集表',
    deliverables: '演示记录、客户预验收反馈清单',
    isEvergreen: false,
  },
  {
    stepNo: '5.4',
    stepName: '问题集中修复 & 回归复测',
    phaseNo: 5,
    department: '开发组、测试组、运维组',
    assigneeRole: '测试工程师',
    durationDays: 5,
    description: '集中修复预验收阶段发现的全部问题，完成回归测试确认修复有效性。',
    notes: '修复过程须避免引入新缺陷，回归测试需覆盖关联功能模块。',
    tools: '缺陷跟踪系统、回归测试工具、版本管理系统',
    deliverables: '缺陷修复确认单、回归测试报告',
    isEvergreen: false,
  },
  {
    stepNo: '5.5',
    stepName: '项目整体正式验收',
    phaseNo: 5,
    department: '客户、销售',
    assigneeRole: '项目经理',
    durationDays: 2,
    description: '组织正式验收评审，客户签署验收报告，确认项目达到合同约定的交付标准。',
    notes: '验收报告须客户盖章确认，未通过验收不得进入运维阶段。',
    tools: '验收报告模板、签章系统、项目文档归档平台',
    deliverables: '正式验收报告、客户签章确认件',
    isEvergreen: false,
  },

  // ──────── Phase 6：运维支持 ────────
  {
    stepNo: '6.1',
    stepName: '系统正式部署上线',
    phaseNo: 6,
    department: '运维组、客户',
    assigneeRole: '运维专员',
    durationDays: 2,
    description: '将系统部署至生产环境，完成数据迁移、域名切换与上线验证，正式对外发布。',
    notes: '上线须制定回滚方案，关键操作需双人复核，上线后持续监控至少24小时。',
    tools: 'CI/CD 平台、监控告警系统、运维管理工具',
    deliverables: '上线部署记录、生产环境验证报告、回滚方案',
    isEvergreen: false,
  },
  {
    stepNo: '6.2',
    stepName: '客户操作 & 资源培训',
    phaseNo: 6,
    department: '客户',
    assigneeRole: '产品经理',
    durationDays: 2,
    description: '为客户提供系统操作培训与管理后台使用指导，确保客户可独立使用系统。',
    notes: '培训须覆盖全部角色操作流程，建议录制培训视频备客户后续查阅。',
    tools: '培训课件、录屏工具、操作手册模板',
    deliverables: '培训课件、操作手册、培训签到记录',
    isEvergreen: false,
  },
  {
    stepNo: '6.3',
    stepName: '日常运维 & 全资源定期巡检',
    phaseNo: 6,
    department: '客户、运维组',
    assigneeRole: '运维专员',
    durationDays: 30,
    description: '提供运维期内日常系统维护，定期巡检服务器、数据库、域名、证书等资源健康状态。',
    notes: '巡检发现问题须及时处理并通知客户，证书到期前30天需主动续期。',
    tools: '监控告警平台、巡检脚本、运维工单系统',
    deliverables: '月度巡检报告、运维工单记录',
    isEvergreen: false,
  },
  {
    stepNo: '6.4',
    stepName: '资源续费、扩容、版本更新',
    phaseNo: 6,
    department: '运维组、销售、客户',
    assigneeRole: '运维专员',
    durationDays: 3,
    description: '跟进服务器、域名、证书等资源续费与扩容需求，执行系统版本更新与补丁部署。',
    notes: '续费操作须提前取得客户书面确认，版本更新需在低峰时段执行并提前通知。',
    tools: '云服务商控制台、续费管理台账、版本发布工具',
    deliverables: '资源续费确认单、版本更新记录',
    isEvergreen: false,
  },
  {
    stepNo: '6.5',
    stepName: '后续版本迭代支持',
    phaseNo: 6,
    department: '客户、开发组、运维组',
    assigneeRole: '产品经理',
    durationDays: 5,
    description: '收集客户后续需求与优化建议，评估后纳入迭代计划并推进开发交付。',
    notes: '新需求如超出合同范围须走变更或增补合同流程，不可直接承诺。',
    tools: '需求管理工具、迭代计划模板、项目管理工具',
    deliverables: '迭代需求清单、迭代计划、迭代交付确认',
    isEvergreen: false,
  },

  // ──────── Phase 7：项目总结 ────────
  {
    stepNo: '7.1',
    stepName: '项目全流程复盘',
    phaseNo: 7,
    department: '全体项目组、管理层',
    assigneeRole: '项目经理',
    durationDays: 2,
    description: '组织项目全员复盘会议，总结经验教训，识别流程改进点，形成复盘报告。',
    notes: '复盘须覆盖工期、质量、成本、客户满意度四个维度，避免流于形式。',
    tools: '复盘会议模板、项目数据统计报表、在线协作白板',
    deliverables: '项目复盘报告、改进建议清单',
    isEvergreen: false,
  },
  {
    stepNo: '7.2',
    stepName: '客户满意度调研',
    phaseNo: 7,
    department: '客户、销售',
    assigneeRole: '产品经理',
    durationDays: 3,
    description: '向客户发送满意度调查问卷，收集对交付质量、响应速度、沟通效果等方面的评价。',
    notes: '满意度结果需真实反馈至管理层，低分项须制定整改计划。',
    tools: '问卷调研工具、满意度评分模板、数据分析工具',
    deliverables: '客户满意度调研报告、整改计划',
    isEvergreen: false,
  },
  {
    stepNo: '7.3',
    stepName: '全套项目 & 资源 & 资质文档归档',
    phaseNo: 7,
    department: '交付组、文档管理员、运维组',
    assigneeRole: '产品经理',
    durationDays: 3,
    description: '将项目全过程文档、资源清单、资质证书等统一整理归档，确保可追溯可复用。',
    notes: '归档须按标准化目录结构，涉密文档需设置访问权限。',
    tools: '文档管理系统、归档目录模板、权限管理平台',
    deliverables: '项目归档清单、归档文档包',
    isEvergreen: false,
  },
  {
    stepNo: '7.4',
    stepName: '客户案例撰写',
    phaseNo: 7,
    department: '销售、市场部',
    assigneeRole: '产品经理',
    durationDays: 5,
    description: '基于项目成果撰写客户案例，提炼业务价值与技术亮点，用于市场推广与销售支持。',
    notes: '案例发布前须取得客户书面授权，避免泄露客户敏感信息。',
    tools: '案例撰写模板、图文编辑工具、审批发布流程',
    deliverables: '客户案例文档、客户授权书',
    isEvergreen: false,
  },
  {
    stepNo: '7.5',
    stepName: '功能库 & 资源流程库维护',
    phaseNo: 7,
    department: '开发组、运维组',
    assigneeRole: '开发主管',
    durationDays: 3,
    description: '将项目中的通用功能模块与运维流程经验沉淀至公司知识库，供后续项目复用。',
    notes: '沉淀内容需经技术评审确认质量，确保可直接复用而非仅供参考。',
    tools: '知识库平台、代码仓库、组件文档工具',
    deliverables: '功能库更新记录、运维流程库更新记录',
    isEvergreen: false,
  },
];
